### PR TITLE
Bindgen support

### LINKED ISSUE #74: bindgen support for macOS target
- [x] Linux: added in #95 
- [x] macOS: added in https://github.com/rust-cross/cargo-zigbuild/pull/99
- [x] Windows gnu: added in https://github.com/rust-cross/cargo-zigbuild/pull/98

### PR DESCRIPTION
**Pull request by HyunggyuJang**
Closes #74
Can you direct me how to implement integration test, or could you do that?

### CODE REVIEW

**Comment by messense** [comment]
Probably just add these command https://github.com/rust-cross/cargo-zigbuild/issues/74#issuecomment-1444862147 in https://github.com/rust-cross/cargo-zigbuild/blob/main/.github/workflows/CI.yml

**Comment by HyunggyuJang** [comment]
> Probably just add these command [#74 (comment)](https://github.com/rust-cross/cargo-zigbuild/issues/74#issuecomment-1444862147) in https://github.com/rust-cross/cargo-zigbuild/blob/main/.github/workflows/CI.yml

Will do that.

**Comment by HyunggyuJang** [comment]
Added CI test. Would it suffice?

**Review by messense — APPROVED** [review]
Thanks!

Currently it's Linux only, probably also need to look into macOS and Windows gnu target support in the future.

**Comment by messense** [comment]
FYI, the unrelated test failures are tracked in https://github.com/rust-cross/cargo-zigbuild/issues/96.

**Pull request merged**
