### PR TITLE
fix zig: unsupported exported_symbols_list

### PR DESCRIPTION
**Pull request by serjflint**
Relates: #164

### CODE REVIEW

**Comment by messense** [comment]
I'm not sure if this actually works because `-exported_symbols_list` takes a value, see https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-exported_symbols_list.

**Comment by messense** [comment]
And looks like it only applies to macOS targets, see https://github.com/rust-lang/rust/blob/dda95c14e1a9356397c6369762047db031e69461/compiler/rustc_codegen_ssa/src/back/linker.rs#L714-L715

**Comment by serjflint** [comment]
> I'm not sure if this actually works because `-exported_symbols_list` takes a value, see https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-exported_symbols_list.

Thanks for pointing that out. Should I do something like [this](https://github.com/rust-cross/cargo-zigbuild/blob/main/src/zig.rs#L175C20-L175C20)?

> And looks like it only applies to macOS targets, see https://github.com/rust-lang/rust/blob/dda95c14e1a9356397c6369762047db031e69461/compiler/rustc_codegen_ssa/src/back/linker.rs#L714-L715

My bad. I haven't checked prior conditions.

I am good at neither Rust nor compiling but I will try to make a PR =)

**Comment by messense** [comment]
> Should I do something like [this](https://github.com/rust-cross/cargo-zigbuild/blob/main/src/zig.rs#L175C20-L175C20)?

I think we need remove both `-Wl,--exported_symbols_list` and the value follows, currently `filter_linker_arg` doesn't support that, so the code needs a bit refactoring.

**Comment by serjflint** [comment]
> I think we need remove both `-Wl,--exported_symbols_list` and the value follows, currently `filter_linker_arg` doesn't support that, so the code needs a bit refactoring.

My case looks like `"-Wl,-exported_symbols_list,/tmp/rustcnkqKsZ/list"` so `arg.starts_with` should do the job.

**Comment by messense** [comment]
What's your Rust version?

**Comment by serjflint** [comment]
> What's your Rust version?

Stable 0.17.2

**Comment by messense** [comment]
OK, so according to the [commit message](https://github.com/rust-lang/rust/commit/32ddd0206c9bd1956f7629c8c76191369f19023f), both `-Wl,-exported_symbols_list,<path>` and `-Wl,-exported_symbols_list <path>` can happen.

So IMO we can merge this first and deal with `-Wl,-exported_symbols_list <path>` later.

**Review by messense — APPROVED** [review]

**Comment by messense** [comment]
Thanks!

**Pull request merged**
